// Mocks generated by Mockito 5.4.6 from annotations
// in field_app/test/services/qr_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:field_app/services/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> loadToken() => (super.noSuchMethod(
        Invocation.method(
          #loadToken,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<dynamic>> getProjects() => (super.noSuchMethod(
        Invocation.method(
          #getProjects,
          [],
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> getWarehouses() => (super.noSuchMethod(
        Invocation.method(
          #getWarehouses,
          [],
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> getMaterials() => (super.noSuchMethod(
        Invocation.method(
          #getMaterials,
          [],
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> getMaterialBySku(String? sku) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMaterialBySku,
          [sku],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<bool> addStockTransaction({
    required int? warehouseId,
    required int? materialId,
    required String? transactionType,
    required int? quantity,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStockTransaction,
          [],
          {
            #warehouseId: warehouseId,
            #materialId: materialId,
            #transactionType: transactionType,
            #quantity: quantity,
            #notes: notes,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<dynamic>> getWarehouseInventory(int? warehouseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWarehouseInventory,
          [warehouseId],
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<String?> uploadDocument({
    required String? filePath,
    required String? fileName,
    required String? fileType,
    int? projectId,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadDocument,
          [],
          {
            #filePath: filePath,
            #fileName: fileName,
            #fileType: fileType,
            #projectId: projectId,
            #description: description,
          },
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> handleQrScan(
          Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleQrScan,
          [payload],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<String> getMaterialQr(int? materialId) => (super.noSuchMethod(
        Invocation.method(
          #getMaterialQr,
          [materialId],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getMaterialQr,
            [materialId],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> registerDeviceToken({
    required String? token,
    required String? deviceType,
    String? deviceName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerDeviceToken,
          [],
          {
            #token: token,
            #deviceType: deviceType,
            #deviceName: deviceName,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> unregisterDeviceToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #unregisterDeviceToken,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getNotificationPreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationPreferences,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> updateNotificationPreferences(
          Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationPreferences,
          [payload],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
